### ISSUE TITLE
How do you program attiny?

### ISSUE THREAD

**Issue by synaption** [nsayer/reboot_o_matic#1]
The board looks like it has a 2x3 header on it.  Is that for programming?  Does it work fully in circuit?  As in, can I remotely program the tiny with the same raspberry pi that I am using the rebootomatic with while I am using it?

**Comment by nsayer** [comment]
You can program it while it’s up. The TPID pin is overloaded as the input trigger pin, so you’d need to be careful and disconnect/hi-Z that pin when not programming it. 

Also, note that you need to use the TPI protocol to do the update, which is a bit specialized. 

Lastly, the functionality here is so simple I’m not sure there’s a lot of justification for live updating. I can see a desire to change the timing rules, but I can’t see that being necessary very often.
